name: Static analysis

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Static analysis

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['8.2', '8.3', '8.4']
      fail-fast: false

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v4

      - run: composer install

      - run: composer phpstan
