name: Unit tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Testing PHP ${{ matrix.php-version }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.0', '8.1', '8.2']

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - uses: actions/checkout@v2

      - run: composer validate

      - run: composer install

      - run: vendor/bin/phpunit --coverage-clover=tests/coverage.xml

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/coverage.xml
