name: Tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Tests

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['8.2', '8.3', '8.4']
      fail-fast: false

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: simplexml
          coverage: pcov

      - uses: actions/checkout@v4

      - run: composer install

      - run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
